#pragma once

#include <stdint.h>

typedef union {
    uint8_t rgba[4];
    uint32_t packed;
    struct { uint8_t r, g, b, a; };
} WarColor;

#define WAR_COLOR_RGB(r, g, b) ((WarColor){{r, g, b, 255}})
#define WAR_COLOR_RGBA(r, g, b, a) ((WarColor){{r, g, b, a}})
#define WAR_COLOR_PACKED(value) ((WarColor){.packed = value})

#define WAR_COLOR_TRANSPARENT WAR_COLOR_PACKED(0x00000000)
#define WAR_COLOR_WHITE WAR_COLOR_PACKED(0xFFFFFFFF)
#define WAR_COLOR_BLACK WAR_COLOR_PACKED(0x000000FF)
#define WAR_COLOR_RED WAR_COLOR_PACKED(0xC70000FF)
#define WAR_COLOR_GREEN WAR_COLOR_PACKED(0x00C700FF)
#define WAR_COLOR_BLUE WAR_COLOR_PACKED(0x0000C7FF)
#define WAR_COLOR_YELLOW WAR_COLOR_PACKED(0xC7C700FF)
#define WAR_COLOR_GRAY_TRANSPARENT WAR_COLOR_PACKED(0x80808080)
#define WAR_COLOR_RED_TRANSPARENT WAR_COLOR_PACKED(0x80000080)
#define WAR_COLOR_GREEN_SELECTION WAR_COLOR_PACKED(0x00C700FF)
#define WAR_COLOR_RED_SELECTION WAR_COLOR_PACKED(0xC70000FF)
#define WAR_COLOR_WHITE_SELECTION WAR_COLOR_PACKED(0xC7C7C7FF)
#define WAR_COLOR_BLUE_INVULNERABLE WAR_COLOR_PACKED(0x0000C7FF)
#define WAR_COLOR_FOG WAR_COLOR_PACKED(0x00000080)
