#pragma once

typedef enum
{
    DB_ENTRY_TYPE_UNKNOWN,
    DB_ENTRY_TYPE_IMAGE,
    DB_ENTRY_TYPE_PALETTE,
    DB_ENTRY_TYPE_XMID,
    DB_ENTRY_TYPE_CURSOR,
    DB_ENTRY_TYPE_UI,
    DB_ENTRY_TYPE_TEXT,
    DB_ENTRY_TYPE_LEVEL_INFO,
    DB_ENTRY_TYPE_LEVEL_VISUAL,
    DB_ENTRY_TYPE_LEVEL_PASSABLE,
    DB_ENTRY_TYPE_SPRITE,
    DB_ENTRY_TYPE_WAVE,
    DB_ENTRY_TYPE_VOC,
    DB_ENTRY_TYPE_TILESET,
    DB_ENTRY_TYPE_TILES,
    DB_ENTRY_TYPE_TABLE
} DatabaseEntryType;

typedef struct
{
    s32 index;
    DatabaseEntryType type;
    char *name;
    u32 param1;
    u32 param2;
    u32 param3;
} DatabaseEntry;

DatabaseEntry assets[] = 
{
    // Music
    {   0, DB_ENTRY_TYPE_XMID,              "00",                                           0, 0, 0 },
    {   1, DB_ENTRY_TYPE_XMID,              "01",                                           0, 0, 0 },
    {   2, DB_ENTRY_TYPE_XMID,              "02",                                           0, 0, 0 },
    {   3, DB_ENTRY_TYPE_XMID,              "03",                                           0, 0, 0 },
    {   4, DB_ENTRY_TYPE_XMID,              "04",                                           0, 0, 0 },
    {   5, DB_ENTRY_TYPE_XMID,              "05",                                           0, 0, 0 },
    {   6, DB_ENTRY_TYPE_XMID,              "06",                                           0, 0, 0 },
    {   7, DB_ENTRY_TYPE_XMID,              "07",                                           0, 0, 0 },
    {   8, DB_ENTRY_TYPE_XMID,              "08",                                           0, 0, 0 },
    {   9, DB_ENTRY_TYPE_XMID,              "09",                                           0, 0, 0 },
    {  10, DB_ENTRY_TYPE_XMID,              "10",                                           0, 0, 0 },
    {  11, DB_ENTRY_TYPE_XMID,              "11",                                           0, 0, 0 },
    {  12, DB_ENTRY_TYPE_XMID,              "12",                                           0, 0, 0 },
    {  13, DB_ENTRY_TYPE_XMID,              "13",                                           0, 0, 0 },
    {  14, DB_ENTRY_TYPE_XMID,              "14",                                           0, 0, 0 },
    {  15, DB_ENTRY_TYPE_XMID,              "15",                                           0, 0, 0 },
    {  16, DB_ENTRY_TYPE_XMID,              "16",                                           0, 0, 0 },
    {  17, DB_ENTRY_TYPE_XMID,              "17",                                           0, 0, 0 },
    {  18, DB_ENTRY_TYPE_XMID,              "18",                                           0, 0, 0 },
    {  19, DB_ENTRY_TYPE_XMID,              "19",                                           0, 0, 0 },
    {  20, DB_ENTRY_TYPE_XMID,              "20",                                           0, 0, 0 },
    {  21, DB_ENTRY_TYPE_XMID,              "21",                                           0, 0, 0 },
    {  22, DB_ENTRY_TYPE_XMID,              "22",                                           0, 0, 0 },
    {  23, DB_ENTRY_TYPE_XMID,              "23",                                           0, 0, 0 },
    {  24, DB_ENTRY_TYPE_XMID,              "24",                                           0, 0, 0 },
    {  25, DB_ENTRY_TYPE_XMID,              "25",                                           0, 0, 0 },
    {  26, DB_ENTRY_TYPE_XMID,              "26",                                           0, 0, 0 },
    {  27, DB_ENTRY_TYPE_XMID,              "27",                                           0, 0, 0 },
    {  28, DB_ENTRY_TYPE_XMID,              "28",                                           0, 0, 0 },
    {  29, DB_ENTRY_TYPE_XMID,              "29",                                           0, 0, 0 },
    {  30, DB_ENTRY_TYPE_XMID,              "30",                                           0, 0, 0 },
    {  31, DB_ENTRY_TYPE_XMID,              "31",                                           0, 0, 0 },
    {  32, DB_ENTRY_TYPE_XMID,              "32",                                           0, 0, 0 },
    {  33, DB_ENTRY_TYPE_XMID,              "33",                                           0, 0, 0 },
    {  34, DB_ENTRY_TYPE_XMID,              "34",                                           0, 0, 0 },
    {  35, DB_ENTRY_TYPE_XMID,              "35",                                           0, 0, 0 },
    {  36, DB_ENTRY_TYPE_XMID,              "36",                                           0, 0, 0 },
    {  37, DB_ENTRY_TYPE_XMID,              "37",                                           0, 0, 0 },
    {  38, DB_ENTRY_TYPE_XMID,              "38",                                           0, 0, 0 },
    {  39, DB_ENTRY_TYPE_XMID,              "39",                                           0, 0, 0 },
    {  40, DB_ENTRY_TYPE_XMID,              "40",                                           0, 0, 0 },
    {  41, DB_ENTRY_TYPE_XMID,              "41",                                           0, 0, 0 },
    {  42, DB_ENTRY_TYPE_XMID,              "42",                                           0, 0, 0 },
    {  43, DB_ENTRY_TYPE_XMID,              "43",                                           0, 0, 0 },
    {  44, DB_ENTRY_TYPE_XMID,              "44",                                           0, 0, 0 },

    // Levels info
    {  45, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    {  46, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },
    {  47, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    {  48, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },
    {  49, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    {  50, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },
    {  51, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    {  52, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },
    {  53, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    {  54, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },
    {  55, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    {  56, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },
    {  57, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    {  58, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },
    {  59, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    {  60, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },
    {  61, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    {  62, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },
    {  63, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    {  64, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },
    {  65, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    {  66, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },
    {  67, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    {  68, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },
    {  69, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    {  70, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },
    {  71, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    {  72, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },
    {  73, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    {  74, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },
    {  75, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    {  76, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },
    {  77, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    {  78, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },
    {  79, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    {  80, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },
    {  81, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    {  82, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },
    {  83, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    {  84, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },
    {  85, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    {  86, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },
    {  87, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    {  88, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },
    {  89, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    {  90, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },
    {  91, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    {  92, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },
    {  93, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    {  94, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },
    {  95, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    {  96, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },
    {  97, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    {  98, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },
    {  99, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    { 100, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },
    { 101, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    { 102, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },
    { 103, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    { 104, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },
    { 105, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    { 106, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },
    { 107, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    { 108, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },
    { 109, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    { 110, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },
    { 111, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    { 112, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },
    { 113, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    { 114, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },
    { 115, DB_ENTRY_TYPE_LEVEL_VISUAL,      "FileLevelVisual",                              0, 0, 0 },
    { 116, DB_ENTRY_TYPE_LEVEL_PASSABLE,    "FileLevelPassable",                            0, 0, 0 },

    // Levels 
    { 117, DB_ENTRY_TYPE_LEVEL_INFO,        "humans_01",                                    0, 0, 0 },
    { 118, DB_ENTRY_TYPE_LEVEL_INFO,        "orcs_01",                                      0, 0, 0 },
    { 119, DB_ENTRY_TYPE_LEVEL_INFO,        "humans_02",                                    0, 0, 0 },
    { 120, DB_ENTRY_TYPE_LEVEL_INFO,        "orcs_02",                                      0, 0, 0 },
    { 121, DB_ENTRY_TYPE_LEVEL_INFO,        "humans_03",                                    0, 0, 0 },
    { 122, DB_ENTRY_TYPE_LEVEL_INFO,        "orcs_03",                                      0, 0, 0 },
    { 123, DB_ENTRY_TYPE_LEVEL_INFO,        "humans_04",                                    0, 0, 0 },
    { 124, DB_ENTRY_TYPE_LEVEL_INFO,        "orcs_04",                                      0, 0, 0 },
    { 125, DB_ENTRY_TYPE_LEVEL_INFO,        "humans_05",                                    0, 0, 0 },
    { 126, DB_ENTRY_TYPE_LEVEL_INFO,        "orcs_05",                                      0, 0, 0 },
    { 127, DB_ENTRY_TYPE_LEVEL_INFO,        "humans_06",                                    0, 0, 0 },
    { 128, DB_ENTRY_TYPE_LEVEL_INFO,        "orcs_06",                                      0, 0, 0 },
    { 129, DB_ENTRY_TYPE_LEVEL_INFO,        "humans_07",                                    0, 0, 0 },
    { 130, DB_ENTRY_TYPE_LEVEL_INFO,        "orcs_07",                                      0, 0, 0 },
    { 131, DB_ENTRY_TYPE_LEVEL_INFO,        "humans_08",                                    0, 0, 0 },
    { 132, DB_ENTRY_TYPE_LEVEL_INFO,        "orcs_08",                                      0, 0, 0 },
    { 133, DB_ENTRY_TYPE_LEVEL_INFO,        "humans_09",                                    0, 0, 0 },
    { 134, DB_ENTRY_TYPE_LEVEL_INFO,        "orcs_09",                                      0, 0, 0 },
    { 135, DB_ENTRY_TYPE_LEVEL_INFO,        "humans_10",                                    0, 0, 0 },
    { 136, DB_ENTRY_TYPE_LEVEL_INFO,        "orcs_10",                                      0, 0, 0 },
    { 137, DB_ENTRY_TYPE_LEVEL_INFO,        "humans_11",                                    0, 0, 0 },
    { 138, DB_ENTRY_TYPE_LEVEL_INFO,        "orcs_11",                                      0, 0, 0 },
    { 139, DB_ENTRY_TYPE_LEVEL_INFO,        "humans_12",                                    0, 0, 0 },
    { 140, DB_ENTRY_TYPE_LEVEL_INFO,        "orcs_12",                                      0, 0, 0 },

    // Palettes
    { 191, DB_ENTRY_TYPE_PALETTE,           "forest",                                       0, 0, 0 },
    { 194, DB_ENTRY_TYPE_PALETTE,           "swamp",                                        0, 0, 0 },
    { 197, DB_ENTRY_TYPE_PALETTE,           "dungeon",                                      0, 0, 0 },
    { 217, DB_ENTRY_TYPE_PALETTE,           "background",                                   0, 0, 0 },
    { 255, DB_ENTRY_TYPE_PALETTE,           "humans",                                       0, 0, 0 },
    { 260, DB_ENTRY_TYPE_PALETTE,           "ui",                                           0, 0, 0 },
    { 262, DB_ENTRY_TYPE_PALETTE,           "pointer",                                      0, 0, 0 },
    { 413, DB_ENTRY_TYPE_PALETTE,           "summary",                                      0, 0, 0 },
    { 416, DB_ENTRY_TYPE_PALETTE,           "for 415",                                      0, 0, 0 },
    { 418, DB_ENTRY_TYPE_PALETTE,           "for 417",                                      0, 0, 0 },
    { 423, DB_ENTRY_TYPE_PALETTE,           "briefing",                                     0, 0, 0 },
    { 424, DB_ENTRY_TYPE_PALETTE,           "briefing",                                     0, 0, 0 },
    { 457, DB_ENTRY_TYPE_PALETTE,           "for 456",                                      0, 0, 0 },
    { 459, DB_ENTRY_TYPE_PALETTE,           "for 458",                                      0, 0, 0 },

    // Tiles
    { 190, DB_ENTRY_TYPE_TILES,             "forest",                                       191, 217, 0 },
    { 193, DB_ENTRY_TYPE_TILES,             "swamp",                                        194, 217, 0 },
    { 196, DB_ENTRY_TYPE_TILES,             "dungeon",                                      197, 217, 0 },

    // Tilesets
    { 189, DB_ENTRY_TYPE_TILESET,           "forest",                                       190, 0, 0 },
    { 192, DB_ENTRY_TYPE_TILESET,           "swamp",                                        193, 0, 0 },
    { 195, DB_ENTRY_TYPE_TILESET,           "dungeon",                                      196, 0, 0 },
    
    // Sprites
    { 279, DB_ENTRY_TYPE_SPRITE,            "footman_humans",                               191, 217, 0 },
    { 280, DB_ENTRY_TYPE_SPRITE,            "grunt_orcs",                                   191, 217, 0 },
    { 281, DB_ENTRY_TYPE_SPRITE,            "peasant_humans",                               191, 217, 0 },
    { 282, DB_ENTRY_TYPE_SPRITE,            "peon_orcs",                                    191, 217, 0 },
    { 283, DB_ENTRY_TYPE_SPRITE,            "catapult_humans",                              191, 217, 0 },
    { 284, DB_ENTRY_TYPE_SPRITE,            "catapult_orcs",                                191, 217, 0 },
    { 285, DB_ENTRY_TYPE_SPRITE,            "knight_humans",                                191, 217, 0 },
    { 286, DB_ENTRY_TYPE_SPRITE,            "raider_orcs",                                  191, 217, 0 },
    { 287, DB_ENTRY_TYPE_SPRITE,            "archer_humans",                                191, 217, 0 },
    { 288, DB_ENTRY_TYPE_SPRITE,            "axethrower_orcs",                              191, 217, 0 },
    { 289, DB_ENTRY_TYPE_SPRITE,            "wizard_humans",                                191, 217, 0 },
    { 290, DB_ENTRY_TYPE_SPRITE,            "wizard_orcs",                                  191, 217, 0 },
    { 291, DB_ENTRY_TYPE_SPRITE,            "priest_humans",                                191, 217, 0 },
    { 292, DB_ENTRY_TYPE_SPRITE,            "necrolyte_orcs",                               191, 217, 0 },
    { 293, DB_ENTRY_TYPE_SPRITE,            "medivh",                                       191, 217, 0 },
    { 294, DB_ENTRY_TYPE_SPRITE,            "lothar",                                       191, 217, 0 },
    { 295, DB_ENTRY_TYPE_SPRITE,            "wounded",                                      191, 217, 0 },
    { 296, DB_ENTRY_TYPE_SPRITE,            "garana",                                       191, 217, 0 },
    { 297, DB_ENTRY_TYPE_SPRITE,            "giant",                                        191, 217, 0 },
    { 298, DB_ENTRY_TYPE_SPRITE,            "spider",                                       191, 217, 0 },
    { 299, DB_ENTRY_TYPE_SPRITE,            "slime",                                        191, 217, 0 },
    { 300, DB_ENTRY_TYPE_SPRITE,            "Unit_300",                                     191, 217, 0 },
    { 301, DB_ENTRY_TYPE_SPRITE,            "scorpion",                                     191, 217, 0 },
    { 302, DB_ENTRY_TYPE_SPRITE,            "brigand",                                      191, 217, 0 },
    { 303, DB_ENTRY_TYPE_SPRITE,            "skeleton_01",                                  191, 217, 0 },
    { 304, DB_ENTRY_TYPE_SPRITE,            "skeleton_02",                                  191, 217, 0 },
    { 305, DB_ENTRY_TYPE_SPRITE,            "demon",                                        191, 217, 0 },
    { 306, DB_ENTRY_TYPE_SPRITE,            "water_elemental",                              191, 217, 0 },
    { 307, DB_ENTRY_TYPE_SPRITE,            "farm_humans",                                  191, 217, 0 },
    { 308, DB_ENTRY_TYPE_SPRITE,            "farm_orcs",                                    191, 217, 0 },
    { 309, DB_ENTRY_TYPE_SPRITE,            "barracks_humans",                              191, 217, 0 },
    { 310, DB_ENTRY_TYPE_SPRITE,            "barracks_orcs",                                191, 217, 0 },
    { 311, DB_ENTRY_TYPE_SPRITE,            "church_humans",                                191, 217, 0 },
    { 312, DB_ENTRY_TYPE_SPRITE,            "temple_orcs",                                  191, 217, 0 },
    { 313, DB_ENTRY_TYPE_SPRITE,            "tower_humns",                                  191, 217, 0 },
    { 314, DB_ENTRY_TYPE_SPRITE,            "skull_orcs",                                   191, 217, 0 },
    { 315, DB_ENTRY_TYPE_SPRITE,            "town_hall_humans",                             191, 217, 0 },
    { 316, DB_ENTRY_TYPE_SPRITE,            "town_hall_orcs",                               191, 217, 0 },
    { 317, DB_ENTRY_TYPE_SPRITE,            "lumbermill_humans",                            191, 217, 0 },
    { 318, DB_ENTRY_TYPE_SPRITE,            "lumbermill_orcs",                              191, 217, 0 },
    { 319, DB_ENTRY_TYPE_SPRITE,            "stable_humans",                                191, 217, 0 },
    { 320, DB_ENTRY_TYPE_SPRITE,            "stable_orcs",                                  191, 217, 0 },
    { 321, DB_ENTRY_TYPE_SPRITE,            "blacksmith_humans",                            191, 217, 0 },
    { 322, DB_ENTRY_TYPE_SPRITE,            "blacksmith_orcs",                              191, 217, 0 },
    { 323, DB_ENTRY_TYPE_SPRITE,            "stormwind_humans",                             191, 217, 0 },
    { 324, DB_ENTRY_TYPE_SPRITE,            "black_spire_orcs",                             191, 217, 0 },
    { 325, DB_ENTRY_TYPE_SPRITE,            "goldmine",                                     191, 217, 0 },
    { 326, DB_ENTRY_TYPE_SPRITE,            "corpse",                                       191, 217, 0 },
    { 327, DB_ENTRY_TYPE_SPRITE,            "peasant_with_lumber_humans",                   191, 217, 0 },
    { 328, DB_ENTRY_TYPE_SPRITE,            "peon_with_lumber_orcs",                        191, 217, 0 },
    { 329, DB_ENTRY_TYPE_SPRITE,            "peasant_with_gold_humans",                     191, 217, 0 },
    { 330, DB_ENTRY_TYPE_SPRITE,            "peon_with_gold_orcs",                          191, 217, 0 },
    { 331, DB_ENTRY_TYPE_SPRITE,            "farm_construction_humans",                     191, 217, 0 },
    { 332, DB_ENTRY_TYPE_SPRITE,            "farm_construction_orcs",                       191, 217, 0 },
    { 333, DB_ENTRY_TYPE_SPRITE,            "barracks_construction_humans",                 191, 217, 0 },
    { 334, DB_ENTRY_TYPE_SPRITE,            "barracks_construction_orcs",                   191, 217, 0 },
    { 335, DB_ENTRY_TYPE_SPRITE,            "church_construction_humans",                   191, 217, 0 },
    { 336, DB_ENTRY_TYPE_SPRITE,            "temple_construction_orcs",                     191, 217, 0 },
    { 337, DB_ENTRY_TYPE_SPRITE,            "tower_construction_humans",                    191, 217, 0 },
    { 338, DB_ENTRY_TYPE_SPRITE,            "tower_construction_orcs",                      191, 217, 0 },
    { 339, DB_ENTRY_TYPE_SPRITE,            "town_hall_construction_humans",                191, 217, 0 },
    { 340, DB_ENTRY_TYPE_SPRITE,            "town_hall_construction_orcs",                  191, 217, 0 },
    { 341, DB_ENTRY_TYPE_SPRITE,            "lumber_mill_construction_humans",              191, 217, 0 },
    { 342, DB_ENTRY_TYPE_SPRITE,            "lumber_mill_construction_orcs",                191, 217, 0 },
    { 343, DB_ENTRY_TYPE_SPRITE,            "stable_construction_humans",                   191, 217, 0 },
    { 344, DB_ENTRY_TYPE_SPRITE,            "stable_construction_orcs",                     191, 217, 0 },
    { 345, DB_ENTRY_TYPE_SPRITE,            "blacksmith_construction_humans",               191, 217, 0 },
    { 346, DB_ENTRY_TYPE_SPRITE,            "blacksmith_construction_orcs",                 191, 217, 0 },
    { 347, DB_ENTRY_TYPE_SPRITE,            "building_explosion",                           191, 217, 0 },
    { 348, DB_ENTRY_TYPE_SPRITE,            "fireball",                                     191, 217, 0 },
    { 349, DB_ENTRY_TYPE_SPRITE,            "arrow",                                        191, 217, 0 },
    { 350, DB_ENTRY_TYPE_SPRITE,            "unit_350",                                     191, 217, 0 },
    { 351, DB_ENTRY_TYPE_SPRITE,            "unit_351",                                     191, 217, 0 },
    { 352, DB_ENTRY_TYPE_SPRITE,            "tornado",                                      191, 217, 0 },
    { 353, DB_ENTRY_TYPE_SPRITE,            "unit_353",                                     191, 217, 0 },
    { 354, DB_ENTRY_TYPE_SPRITE,            "unit_354",                                     191, 217, 0 },
    { 355, DB_ENTRY_TYPE_SPRITE,            "unit_355",                                     191, 217, 0 },
    { 356, DB_ENTRY_TYPE_SPRITE,            "unit_356",                                     191, 217, 0 },
    { 357, DB_ENTRY_TYPE_SPRITE,            "unit_357",                                     191, 217, 0 },
    { 358, DB_ENTRY_TYPE_SPRITE,            "unit_358",                                     191, 217, 0 },
    { 359, DB_ENTRY_TYPE_SPRITE,            "ui_pictures_orcs",                             191, 217, 0 },
    { 360, DB_ENTRY_TYPE_SPRITE,            "ui_pictures_humans",                           191, 255, 0 },
    { 361, DB_ENTRY_TYPE_SPRITE,            "ui_pictures_cons",                             191, 217, 0 },
    { 425, DB_ENTRY_TYPE_SPRITE,            "burning_fire",                                 424,   0, 0 },
    { 426, DB_ENTRY_TYPE_SPRITE,            "talking_orc_01",                               424,   0, 0 },
    { 427, DB_ENTRY_TYPE_SPRITE,            "talking_orc_02",                               424,   0, 0 },
    { 428, DB_ENTRY_TYPE_SPRITE,            "eating_human",                                 423,   0, 0 },
    { 429, DB_ENTRY_TYPE_SPRITE,            "human_wizard",                                 423,   0, 0 },
    { 430, DB_ENTRY_TYPE_SPRITE,            "anim_01",                                      423,   0, 0 },
    { 431, DB_ENTRY_TYPE_SPRITE,            "anim_02",                                      423,   0, 0 },
    { 460, DB_ENTRY_TYPE_SPRITE,            "anim_03",                                      459,   0, 0 },

    // Images
    { 216, DB_ENTRY_TYPE_IMAGE,             "background 'Blizzard'",                        217,   0, 0 },
    { 218, DB_ENTRY_TYPE_IMAGE,             "topbar_humans",                                255,   0, 0 },
    { 219, DB_ENTRY_TYPE_IMAGE,             "topbar_orcs",                                  191, 217, 0 },
    { 220, DB_ENTRY_TYPE_IMAGE,             "sidebar_right_humans",                         255,   0, 0 },
    { 221, DB_ENTRY_TYPE_IMAGE,             "sidebar_right_orcs",                           217,   0, 0 },
    { 222, DB_ENTRY_TYPE_IMAGE,             "lower_bar_humans",                             255,   0, 0 },
    { 223, DB_ENTRY_TYPE_IMAGE,             "lower_bar_orcs",                               217,   0, 0 },
    { 224, DB_ENTRY_TYPE_IMAGE,             "sidebar_left_minimap_empty_humans",            255,   0, 0 },
    { 225, DB_ENTRY_TYPE_IMAGE,             "sidebar_left_minimap_empty_orcs",              217,   0, 0 },
    { 226, DB_ENTRY_TYPE_IMAGE,             "sidebar_left_humans",                          255,   0, 0 },
    { 227, DB_ENTRY_TYPE_IMAGE,             "sidebar_left_orcs",                            217,   0, 0 },
    { 228, DB_ENTRY_TYPE_IMAGE,             "sidebar_left_minimap_black_humans",            255,   0, 0 },
    { 229, DB_ENTRY_TYPE_IMAGE,             "sidebar_left_minimap_black_orcs",              217,   0, 0 },
    { 233, DB_ENTRY_TYPE_IMAGE,             "large_box_humans",                             255,   0, 0 },
    { 234, DB_ENTRY_TYPE_IMAGE,             "large_box_orcs",                               217,   0, 0 },
    { 235, DB_ENTRY_TYPE_IMAGE,             "small_box_humans",                             255,   0, 0 },
    { 236, DB_ENTRY_TYPE_IMAGE,             "smal_box_orcs",                                217,   0, 0 },
    { 237, DB_ENTRY_TYPE_IMAGE,             "large_button",                                 260,   0, 0 },
    { 238, DB_ENTRY_TYPE_IMAGE,             "large_button_pressed",                         260,   0, 0 },
    { 239, DB_ENTRY_TYPE_IMAGE,             "medium_button",                                260,   0, 0 },
    { 240, DB_ENTRY_TYPE_IMAGE,             "medium_button_pressed",                        260,   0, 0 },
    { 241, DB_ENTRY_TYPE_IMAGE,             "small_button",                                 260,   0, 0 },
    { 242, DB_ENTRY_TYPE_IMAGE,             "small_button_pressed",                         260,   0, 0 },
    { 243, DB_ENTRY_TYPE_IMAGE,             "menu_background_lower",                        260,   0, 0 },
    { 244, DB_ENTRY_TYPE_IMAGE,             "arrow_left_button",                            255,   0, 0 },
    { 245, DB_ENTRY_TYPE_IMAGE,             "arrow_left_button_grey",                       255,   0, 0 },
    { 246, DB_ENTRY_TYPE_IMAGE,             "arrow_right_button",                           255,   0, 0 },
    { 247, DB_ENTRY_TYPE_IMAGE,             "arrow_right_button_grey",                      255,   0, 0 },
    { 248, DB_ENTRY_TYPE_IMAGE,             "window_border",                                255,   0, 0 },
    { 249, DB_ENTRY_TYPE_IMAGE,             "saving_loading_humans",                        255,   0, 0 },
    { 250, DB_ENTRY_TYPE_IMAGE,             "saving_loading_orcs",                          217,   0, 0 },
    { 254, DB_ENTRY_TYPE_IMAGE,             "hot_keys",                                     255,   0, 0 },
    { 256, DB_ENTRY_TYPE_IMAGE,             "ok1_button",                                   255,   0, 0 },
    { 257, DB_ENTRY_TYPE_IMAGE,             "ok2_button",                                   255,   0, 0 },
    { 258, DB_ENTRY_TYPE_IMAGE,             "warcraft_text",                                260,   0, 0 },
    { 261, DB_ENTRY_TYPE_IMAGE,             "menu_background",                              260,   0, 0 },
    { 362, DB_ENTRY_TYPE_IMAGE,             "menu_button",                                  217,   0, 0 }, 
    { 363, DB_ENTRY_TYPE_IMAGE,             "menu_button_pressed",                          217,   0, 0 },
    { 364, DB_ENTRY_TYPE_IMAGE,             "empty_button",                                 255,   0, 0 }, 
    { 365, DB_ENTRY_TYPE_IMAGE,             "empty_button_pressed",                         217,   0, 0 }, 
    { 406, DB_ENTRY_TYPE_IMAGE,             "gold_humans",                                  191, 217, 0 },
    { 407, DB_ENTRY_TYPE_IMAGE,             "lumber_humans",                                217,   0, 0 },
    { 408, DB_ENTRY_TYPE_IMAGE,             "gold_orcs",                                    191, 217, 0 },
    { 409, DB_ENTRY_TYPE_IMAGE,             "lumber_orcs",                                  217,   0, 0 },
    { 410, DB_ENTRY_TYPE_IMAGE,             "percent_complete",                             217,   0, 0 },
    { 411, DB_ENTRY_TYPE_IMAGE,             "points_summary_humans",                        413,   0, 0 },
    { 412, DB_ENTRY_TYPE_IMAGE,             "points_summary_orcs",                          413,   0, 0 },
    { 415, DB_ENTRY_TYPE_IMAGE,             "victory_background",                           416,   0, 0 },
    { 417, DB_ENTRY_TYPE_IMAGE,             "defeat_background",                            418,   0, 0 },
    { 419, DB_ENTRY_TYPE_IMAGE,             "victory_text",                                 423,   0, 0 },
    { 420, DB_ENTRY_TYPE_IMAGE,             "defeat_text",                                  423,   0, 0 },
    { 421, DB_ENTRY_TYPE_IMAGE,             "briefing_humans",                              423,   0, 0 },
    { 422, DB_ENTRY_TYPE_IMAGE,             "briefing_orcs",                                424,   0, 0 },
    { 456, DB_ENTRY_TYPE_IMAGE,             "win_humans",                                   457,   0, 0 },
    { 458, DB_ENTRY_TYPE_IMAGE,             "win_orcs",                                     459,   0, 0 },
    { 470, DB_ENTRY_TYPE_IMAGE,             "win_anim_humans",                              457,   0, 0 },
    { 471, DB_ENTRY_TYPE_IMAGE,             "win_anim_orcs",                                260,   0, 0 },
};
