#pragma once

#include <stdint.h>

typedef union {
    uint32_t packed;
    uint8_t rgba[4];
    struct { uint8_t r, g, b, a; };
} WarColor;

#define WAR_COLOR_RGBA_INIT(r_, g_, b_, a_) {.r = r_, .g = g_, .b = b_, .a = a_}
#define WAR_COLOR_RGBA(r_, g_, b_, a_) ((WarColor)WAR_COLOR_RGBA_INIT(r_, g_, b_, a_))

#define WAR_COLOR_RGB_INIT(r_, g_, b_) WAR_COLOR_RGBA_INIT(r_, g_, b_, 255)
#define WAR_COLOR_RGB(r_, g_, b_) WAR_COLOR_RGBA(r_, g_, b_, 255)

#define WAR_COLOR_PACKED_INIT(value) { .packed = (uint32_t)(value) }
#define WAR_COLOR_PACKED(value) ((WarColor)WAR_COLOR_PACKED_INIT(value))

#define WAR_COLOR_TRANSPARENT WAR_COLOR_PACKED(0x00000000)
#define WAR_COLOR_WHITE WAR_COLOR_PACKED(0xFFFFFFFF)
#define WAR_COLOR_BLACK WAR_COLOR_PACKED(0x000000FF)
#define WAR_COLOR_RED WAR_COLOR_PACKED(0xC70000FF)
#define WAR_COLOR_GREEN WAR_COLOR_PACKED(0x00C700FF)
#define WAR_COLOR_BLUE WAR_COLOR_PACKED(0x0000C7FF)
#define WAR_COLOR_YELLOW WAR_COLOR_PACKED(0xC7C700FF)
#define WAR_COLOR_GRAY_TRANSPARENT WAR_COLOR_PACKED(0x80808080)
#define WAR_COLOR_RED_TRANSPARENT WAR_COLOR_PACKED(0x80000080)
#define WAR_COLOR_GREEN_SELECTION WAR_COLOR_PACKED(0x00C700FF)
#define WAR_COLOR_RED_SELECTION WAR_COLOR_PACKED(0xC70000FF)
#define WAR_COLOR_WHITE_SELECTION WAR_COLOR_PACKED(0xC7C7C7FF)
#define WAR_COLOR_BLUE_INVULNERABLE WAR_COLOR_PACKED(0x0000C7FF)
#define WAR_COLOR_FOG WAR_COLOR_PACKED(0x00000080)
