#pragma once

// NOTE: All the enums in the game are defined here
// Cannot forward declare enums in C, as it's not allowed by the C standard

typedef enum
{
    DB_ENTRY_TYPE_UNKNOWN,
    DB_ENTRY_TYPE_IMAGE,
    DB_ENTRY_TYPE_PALETTE,
    DB_ENTRY_TYPE_XMID,
    DB_ENTRY_TYPE_CURSOR,
    DB_ENTRY_TYPE_UI,
    DB_ENTRY_TYPE_TEXT,
    DB_ENTRY_TYPE_LEVEL_INFO,
    DB_ENTRY_TYPE_LEVEL_VISUAL,
    DB_ENTRY_TYPE_LEVEL_PASSABLE,
    DB_ENTRY_TYPE_SPRITE,
    DB_ENTRY_TYPE_WAVE,
    DB_ENTRY_TYPE_VOC,
    DB_ENTRY_TYPE_TILESET,
    DB_ENTRY_TYPE_TILES
} DatabaseEntryType;

typedef enum _WarMouseButtons
{
    WAR_MOUSE_LEFT,
    WAR_MOUSE_RIGHT,

    WAR_MOUSE_COUNT
} WarMouseButtons;

typedef enum _WarKeys
{
    WAR_KEY_NONE,

    WAR_KEY_SPACE,
    WAR_KEY_APOSTROPHE,
    WAR_KEY_ASTERISK,
    WAR_KEY_PLUS,
    WAR_KEY_COMMA,
    WAR_KEY_MINUS,
    WAR_KEY_PERIOD,
    WAR_KEY_SLASH,

    WAR_KEY_0,
    WAR_KEY_1,
    WAR_KEY_2,
    WAR_KEY_3,
    WAR_KEY_4,
    WAR_KEY_5,
    WAR_KEY_6,
    WAR_KEY_7,
    WAR_KEY_8,
    WAR_KEY_9,

    WAR_KEY_SEMICOLON,
    WAR_KEY_EQUAL,

    WAR_KEY_A,
    WAR_KEY_B,
    WAR_KEY_C,
    WAR_KEY_D,
    WAR_KEY_E,
    WAR_KEY_F,
    WAR_KEY_G,
    WAR_KEY_H,
    WAR_KEY_I,
    WAR_KEY_J,
    WAR_KEY_K,
    WAR_KEY_L,
    WAR_KEY_M,
    WAR_KEY_N,
    WAR_KEY_O,
    WAR_KEY_P,
    WAR_KEY_Q,
    WAR_KEY_R,
    WAR_KEY_S,
    WAR_KEY_T,
    WAR_KEY_U,
    WAR_KEY_V,
    WAR_KEY_W,
    WAR_KEY_X,
    WAR_KEY_Y,
    WAR_KEY_Z,

    WAR_KEY_LEFT_BRACKET,
    WAR_KEY_BACKSLASH,
    WAR_KEY_RIGHT_BRACKET,
    WAR_KEY_GRAVE_ACCENT,

    WAR_KEY_ESC,
    WAR_KEY_ENTER,
    WAR_KEY_TAB,
    WAR_KEY_BACKSPACE,
    WAR_KEY_INSERT,
    WAR_KEY_DELETE,

    WAR_KEY_RIGHT,
    WAR_KEY_LEFT,
    WAR_KEY_DOWN,
    WAR_KEY_UP,

    WAR_KEY_PAGE_UP,
    WAR_KEY_PAGE_DOWN,
    WAR_KEY_HOME,
    WAR_KEY_END,

    WAR_KEY_F1,
    WAR_KEY_F2,
    WAR_KEY_F3,
    WAR_KEY_F4,
    WAR_KEY_F5,
    WAR_KEY_F6,
    WAR_KEY_F7,
    WAR_KEY_F8,
    WAR_KEY_F9,
    WAR_KEY_F10,
    WAR_KEY_F11,
    WAR_KEY_F12,

    WAR_KEY_SHIFT,
    WAR_KEY_CTRL,
    WAR_KEY_ALT,

    WAR_KEY_COUNT
} WarKeys;

typedef enum _WarFileType
{
    WAR_FILE_TYPE_UNKNOWN,
    WAR_FILE_TYPE_DEMO,
    WAR_FILE_TYPE_RETAIL
} WarFileType;

typedef enum _WarResourceType
{
    WAR_RESOURCE_TYPE_UNKNOWN,
    WAR_RESOURCE_TYPE_IMAGE,
    WAR_RESOURCE_TYPE_PALETTE,
    WAR_RESOURCE_TYPE_XMID,
    WAR_RESOURCE_TYPE_CURSOR,
    WAR_RESOURCE_TYPE_UI,
    WAR_RESOURCE_TYPE_TEXT,
    WAR_RESOURCE_TYPE_LEVEL_INFO,
    WAR_RESOURCE_TYPE_LEVEL_VISUAL,
    WAR_RESOURCE_TYPE_LEVEL_PASSABLE,
    WAR_RESOURCE_TYPE_SPRITE,
    WAR_RESOURCE_TYPE_WAVE,
    WAR_RESOURCE_TYPE_VOC,
    WAR_RESOURCE_TYPE_TILESET,
    WAR_RESOURCE_TYPE_TILES
} WarResourceType;

typedef enum _WarLevelInfoType
{
    WAR_LEVEL_TYPE_UNKOWN,
    WAR_LEVEL_TYPE_1,
    WAR_LEVEL_TYPE_2,
    WAR_LEVEL_TYPE_3
} WarLevelInfoType;

typedef enum _WarRace
{
    WAR_RACE_NEUTRAL,
    WAR_RACE_HUMANS,
    WAR_RACE_ORCS
} WarRace;

typedef enum _WarUnitDirection
{
    WAR_DIRECTION_NORTH,
    WAR_DIRECTION_NORTH_EAST,
    WAR_DIRECTION_EAST,
    WAR_DIRECTION_SOUTH_EAST,
    WAR_DIRECTION_SOUTH,
    WAR_DIRECTION_SOUTH_WEST,
    WAR_DIRECTION_WEST,
    WAR_DIRECTION_NORTH_WEST,

    WAR_DIRECTION_COUNT
} WarUnitDirection;

typedef enum _WarUnitType
{
    // units
    WAR_UNIT_FOOTMAN,
    WAR_UNIT_GRUNT,
    WAR_UNIT_PEASANT,
    WAR_UNIT_PEON,
    WAR_UNIT_CATAPULT_HUMANS,
    WAR_UNIT_CATAPULT_ORCS,
    WAR_UNIT_KNIGHT,
    WAR_UNIT_RAIDER,
    WAR_UNIT_ARCHER,
    WAR_UNIT_SPEARMAN,
    WAR_UNIT_CONJURER,
    WAR_UNIT_WARLOCK,
    WAR_UNIT_CLERIC,
    WAR_UNIT_NECROLYTE,
    WAR_UNIT_MEDIVH,
    WAR_UNIT_LOTHAR,
    WAR_UNIT_WOUNDED,
    WAR_UNIT_GRIZELDA,
    WAR_UNIT_GARONA,
    WAR_UNIT_OGRE,
    WAR_UNIT_SPIDER,
    WAR_UNIT_SLIME,
    WAR_UNIT_FIRE_ELEMENTAL,
    WAR_UNIT_SCORPION,
    WAR_UNIT_BRIGAND,
    WAR_UNIT_THE_DEAD,
    WAR_UNIT_SKELETON,
    WAR_UNIT_DAEMON,
    WAR_UNIT_WATER_ELEMENTAL,
    WAR_UNIT_DRAGON_CYCLOPS_GIANT,
    WAR_UNIT_26,
    WAR_UNIT_30,

    // buildings
    WAR_UNIT_FARM_HUMANS,
    WAR_UNIT_FARM_ORCS,
    WAR_UNIT_BARRACKS_HUMANS,
    WAR_UNIT_BARRACKS_ORCS,
    WAR_UNIT_CHURCH,
    WAR_UNIT_TEMPLE,
    WAR_UNIT_TOWER_HUMANS,
    WAR_UNIT_TOWER_ORCS,
    WAR_UNIT_TOWNHALL_HUMANS,
    WAR_UNIT_TOWNHALL_ORCS,
    WAR_UNIT_LUMBERMILL_HUMANS,
    WAR_UNIT_LUMBERMILL_ORCS,
    WAR_UNIT_STABLE,
    WAR_UNIT_KENNEL,
    WAR_UNIT_BLACKSMITH_HUMANS,
    WAR_UNIT_BLACKSMITH_ORCS,
    WAR_UNIT_STORMWIND,
    WAR_UNIT_BLACKROCK,

    // neutral
    WAR_UNIT_GOLDMINE,

	WAR_UNIT_51,

    // others
    WAR_UNIT_HUMAN_CORPSE,
    WAR_UNIT_ORC_CORPSE,

    WAR_UNIT_COUNT
} WarUnitType;

typedef enum _WarAnimationStatus
{
    WAR_ANIM_STATUS_NOT_STARTED,
    WAR_ANIM_STATUS_RUNNING,
    WAR_ANIM_STATUS_FINISHED
} WarAnimationStatus;

typedef enum _WarResourceKind
{
    WAR_RESOURCE_NONE,
    WAR_RESOURCE_GOLD,
    WAR_RESOURCE_WOOD
} WarResourceKind;

typedef enum _WarConstructType
{
    WAR_CONSTRUCT_UNKOWN,
    WAR_CONSTRUCT_ROAD,
    WAR_CONSTRUCT_WALL
} WarConstructType;

typedef enum _WarCampaignMapType
{
    WAR_CAMPAIGN_HUMANS_01 = 117,
    WAR_CAMPAIGN_ORCS_01,
    WAR_CAMPAIGN_HUMANS_02,
    WAR_CAMPAIGN_ORCS_02,
    WAR_CAMPAIGN_HUMANS_03,
    WAR_CAMPAIGN_ORCS_03,
    WAR_CAMPAIGN_HUMANS_04,
    WAR_CAMPAIGN_ORCS_04,
    WAR_CAMPAIGN_HUMANS_05,
    WAR_CAMPAIGN_ORCS_05,
    WAR_CAMPAIGN_HUMANS_06,
    WAR_CAMPAIGN_ORCS_06,
    WAR_CAMPAIGN_HUMANS_07,
    WAR_CAMPAIGN_ORCS_07,
    WAR_CAMPAIGN_HUMANS_08,
    WAR_CAMPAIGN_ORCS_08,
    WAR_CAMPAIGN_HUMANS_09,
    WAR_CAMPAIGN_ORCS_09,
    WAR_CAMPAIGN_HUMANS_10,
    WAR_CAMPAIGN_ORCS_10,
    WAR_CAMPAIGN_HUMANS_11,
    WAR_CAMPAIGN_ORCS_11,
    WAR_CAMPAIGN_HUMANS_12,
    WAR_CAMPAIGN_ORCS_12,
    WAR_CAMPAIGN_CUSTOM
} WarCampaignMapType;

typedef enum _WarLevelResult
{
    WAR_LEVEL_RESULT_NONE,
    WAR_LEVEL_RESULT_WIN,
    WAR_LEVEL_RESULT_LOSE
} WarLevelResult;

typedef enum _WarFeatureType
{
    WAR_FEATURE_UNIT_FOOTMAN,
    WAR_FEATURE_UNIT_GRUNT,
    WAR_FEATURE_UNIT_PEASANT,
    WAR_FEATURE_UNIT_PEON,
    WAR_FEATURE_UNIT_CATAPULT_HUMANS,
    WAR_FEATURE_UNIT_CATAPULT_ORCS,
    WAR_FEATURE_UNIT_KNIGHT,
    WAR_FEATURE_UNIT_RAIDER,
    WAR_FEATURE_UNIT_ARCHER,
    WAR_FEATURE_UNIT_SPEARMAN,
    WAR_FEATURE_UNIT_CONJURER,
    WAR_FEATURE_UNIT_WARLOCK,
    WAR_FEATURE_UNIT_CLERIC,
    WAR_FEATURE_UNIT_NECROLYTE,
    WAR_FEATURE_UNIT_FARM_HUMANS,
    WAR_FEATURE_UNIT_FARM_ORCS,
    WAR_FEATURE_UNIT_BARRACKS_HUMANS,
    WAR_FEATURE_UNIT_BARRACKS_ORCS,
    WAR_FEATURE_UNIT_CHURCH,
    WAR_FEATURE_UNIT_TEMPLE,
    WAR_FEATURE_UNIT_TOWER_HUMANS,
    WAR_FEATURE_UNIT_TOWER_ORCS,
    WAR_FEATURE_UNIT_TOWN_HALL_HUMANS,
    WAR_FEATURE_UNIT_TOWN_HALL_ORCS,
    WAR_FEATURE_UNIT_LUMBER_MILL_HUMANS,
    WAR_FEATURE_UNIT_LUMBER_MILL_ORCS,
    WAR_FEATURE_UNIT_STABLE,
    WAR_FEATURE_UNIT_KENNEL,
    WAR_FEATURE_UNIT_BLACKSMITH_HUMANS,
    WAR_FEATURE_UNIT_BLACKSMITH_ORCS,
    WAR_FEATURE_SPELL_HEALING,
    WAR_FEATURE_SPELL_RAISE_DEAD,
    WAR_FEATURE_SPELL_FAR_SIGHT,
    WAR_FEATURE_SPELL_DARK_VISION,
    WAR_FEATURE_SPELL_INVISIBILITY,
    WAR_FEATURE_SPELL_UNHOLY_ARMOR,
    WAR_FEATURE_SPELL_SCORPION,
    WAR_FEATURE_SPELL_SPIDER,
    WAR_FEATURE_SPELL_RAIN_OF_FIRE,
    WAR_FEATURE_SPELL_POISON_CLOUD,
    WAR_FEATURE_SPELL_WATER_ELEMENTAL,
    WAR_FEATURE_SPELL_DAEMON,
    WAR_FEATURE_UNIT_ROAD,
    WAR_FEATURE_UNIT_WALL,
} WarFeatureType;

typedef enum _WarUpgradeType
{
    WAR_UPGRADE_ARROWS,
    WAR_UPGRADE_SPEARS,
    WAR_UPGRADE_SWORDS,
    WAR_UPGRADE_AXES,
    WAR_UPGRADE_HORSES,
    WAR_UPGRADE_WOLVES,
    WAR_UPGRADE_SCORPIONS,
    WAR_UPGRADE_SPIDERS,
    WAR_UPGRADE_RAIN_OF_FIRE,
    WAR_UPGRADE_POISON_CLOUD,
    WAR_UPGRADE_WATER_ELEMENTAL,
    WAR_UPGRADE_DAEMON,
    WAR_UPGRADE_HEALING,
    WAR_UPGRADE_RAISE_DEAD,
    WAR_UPGRADE_FAR_SIGHT,
    WAR_UPGRADE_DARK_VISION,
    WAR_UPGRADE_INVISIBILITY,
    WAR_UPGRADE_UNHOLY_ARMOR,
    WAR_UPGRADE_SHIELD
} WarUpgradeType;

typedef enum _WarSpellType
{
    // spells
    WAR_SPELL_HEALING,
    WAR_SPELL_FAR_SIGHT,
    WAR_SPELL_INVISIBILITY,
    WAR_SPELL_RAIN_OF_FIRE,
    WAR_SPELL_POISON_CLOUD,
    WAR_SPELL_RAISE_DEAD,
    WAR_SPELL_DARK_VISION,
    WAR_SPELL_UNHOLY_ARMOR,

    // summons
    WAR_SUMMON_SPIDER,
    WAR_SUMMON_SCORPION,
    WAR_SUMMON_DAEMON,
    WAR_SUMMON_WATER_ELEMENTAL,
} WarSpellType;

typedef enum _WarUnitCommandType
{
    WAR_COMMAND_NONE, // 0

    // unit commands
    WAR_COMMAND_MOVE, // 1
    WAR_COMMAND_STOP,
    WAR_COMMAND_HARVEST,
    WAR_COMMAND_DELIVER,
    WAR_COMMAND_REPAIR,
    WAR_COMMAND_ATTACK,

    // train commands
    WAR_COMMAND_TRAIN_FOOTMAN, // 7
    WAR_COMMAND_TRAIN_GRUNT,
    WAR_COMMAND_TRAIN_PEASANT,
    WAR_COMMAND_TRAIN_PEON,
    WAR_COMMAND_TRAIN_CATAPULT_HUMANS,
    WAR_COMMAND_TRAIN_CATAPULT_ORCS,
    WAR_COMMAND_TRAIN_KNIGHT,
    WAR_COMMAND_TRAIN_RAIDER,
    WAR_COMMAND_TRAIN_ARCHER,
    WAR_COMMAND_TRAIN_SPEARMAN,
    WAR_COMMAND_TRAIN_CONJURER,
    WAR_COMMAND_TRAIN_WARLOCK,
    WAR_COMMAND_TRAIN_CLERIC,
    WAR_COMMAND_TRAIN_NECROLYTE,

    // spell commands
    WAR_COMMAND_SPELL_HEALING, // 21
    WAR_COMMAND_SPELL_FAR_SIGHT,
    WAR_COMMAND_SPELL_INVISIBILITY,
    WAR_COMMAND_SPELL_RAIN_OF_FIRE,
    WAR_COMMAND_SPELL_POISON_CLOUD,
    WAR_COMMAND_SPELL_RAISE_DEAD,
    WAR_COMMAND_SPELL_DARK_VISION,
    WAR_COMMAND_SPELL_UNHOLY_ARMOR,

    // summons
    WAR_COMMAND_SUMMON_SPIDER, // 29
    WAR_COMMAND_SUMMON_SCORPION,
    WAR_COMMAND_SUMMON_DAEMON,
    WAR_COMMAND_SUMMON_WATER_ELEMENTAL,

    // build commands
    WAR_COMMAND_BUILD_BASIC, // 33
    WAR_COMMAND_BUILD_ADVANCED,
    WAR_COMMAND_BUILD_FARM_HUMANS,
    WAR_COMMAND_BUILD_FARM_ORCS,
    WAR_COMMAND_BUILD_BARRACKS_HUMANS,
    WAR_COMMAND_BUILD_BARRACKS_ORCS,
    WAR_COMMAND_BUILD_CHURCH,
    WAR_COMMAND_BUILD_TEMPLE,
    WAR_COMMAND_BUILD_TOWER_HUMANS,
    WAR_COMMAND_BUILD_TOWER_ORCS,
    WAR_COMMAND_BUILD_TOWNHALL_HUMANS,
    WAR_COMMAND_BUILD_TOWNHALL_ORCS,
    WAR_COMMAND_BUILD_LUMBERMILL_HUMANS,
    WAR_COMMAND_BUILD_LUMBERMILL_ORCS,
    WAR_COMMAND_BUILD_STABLE,
    WAR_COMMAND_BUILD_KENNEL,
    WAR_COMMAND_BUILD_BLACKSMITH_HUMANS,
    WAR_COMMAND_BUILD_BLACKSMITH_ORCS,
    WAR_COMMAND_BUILD_ROAD,
    WAR_COMMAND_BUILD_WALL,

    // upgrades
    WAR_COMMAND_UPGRADE_SWORDS, // 53
    WAR_COMMAND_UPGRADE_AXES,
    WAR_COMMAND_UPGRADE_SHIELD_HUMANS,
    WAR_COMMAND_UPGRADE_SHIELD_ORCS,
    WAR_COMMAND_UPGRADE_ARROWS,
    WAR_COMMAND_UPGRADE_SPEARS,
    WAR_COMMAND_UPGRADE_HORSES,
    WAR_COMMAND_UPGRADE_WOLVES,
    WAR_COMMAND_UPGRADE_SCORPION,
    WAR_COMMAND_UPGRADE_SPIDER,
    WAR_COMMAND_UPGRADE_RAIN_OF_FIRE,
    WAR_COMMAND_UPGRADE_POISON_CLOUD,
    WAR_COMMAND_UPGRADE_WATER_ELEMENTAL,
    WAR_COMMAND_UPGRADE_DAEMON,
    WAR_COMMAND_UPGRADE_HEALING,
    WAR_COMMAND_UPGRADE_RAISE_DEAD,
    WAR_COMMAND_UPGRADE_FAR_SIGHT,
    WAR_COMMAND_UPGRADE_DARK_VISION,
    WAR_COMMAND_UPGRADE_INVISIBILITY,
    WAR_COMMAND_UPGRADE_UNHOLY_ARMOR,

    // wcmd_cancel
    WAR_COMMAND_CANCEL // 73
} WarUnitCommandType;

typedef enum _WarEntityType
{
    WAR_ENTITY_TYPE_NONE,
    WAR_ENTITY_TYPE_IMAGE,
    WAR_ENTITY_TYPE_UNIT,
    WAR_ENTITY_TYPE_ROAD,
    WAR_ENTITY_TYPE_WALL,
    WAR_ENTITY_TYPE_RUIN,
    WAR_ENTITY_TYPE_FOREST,
    WAR_ENTITY_TYPE_TEXT,
    WAR_ENTITY_TYPE_RECT,
    WAR_ENTITY_TYPE_BUTTON,
    WAR_ENTITY_TYPE_CURSOR,
    WAR_ENTITY_TYPE_AUDIO,
    WAR_ENTITY_TYPE_PROJECTILE,
    WAR_ENTITY_TYPE_RAIN_OF_FIRE,
    WAR_ENTITY_TYPE_POISON_CLOUD,
    WAR_ENTITY_TYPE_SIGHT,
    WAR_ENTITY_TYPE_MINIMAP,
    WAR_ENTITY_TYPE_ANIMATION,

    WAR_ENTITY_TYPE_COUNT
} WarEntityType;

typedef enum _WarRoadPieceType
{
    WAR_ROAD_PIECE_LEFT,
    WAR_ROAD_PIECE_TOP,
    WAR_ROAD_PIECE_RIGHT,
    WAR_ROAD_PIECE_BOTTOM,
    WAR_ROAD_PIECE_BOTTOM_LEFT,
    WAR_ROAD_PIECE_VERTICAL,
    WAR_ROAD_PIECE_BOTTOM_RIGHT,
    WAR_ROAD_PIECE_T_LEFT,
    WAR_ROAD_PIECE_T_BOTTOM,
    WAR_ROAD_PIECE_T_RIGHT,
    WAR_ROAD_PIECE_CROSS,
    WAR_ROAD_PIECE_TOP_LEFT,
    WAR_ROAD_PIECE_HORIZONTAL,
    WAR_ROAD_PIECE_T_TOP,
    WAR_ROAD_PIECE_TOP_RIGHT,
} WarRoadPieceType;

typedef enum _WarWallPieceType
{
    WAR_WALL_PIECE_LEFT,
    WAR_WALL_PIECE_TOP,
    WAR_WALL_PIECE_RIGHT,
    WAR_WALL_PIECE_BOTTOM,
    WAR_WALL_PIECE_BOTTOM_LEFT,
    WAR_WALL_PIECE_VERTICAL,
    WAR_WALL_PIECE_BOTTOM_RIGHT,
    WAR_WALL_PIECE_T_LEFT,
    WAR_WALL_PIECE_T_BOTTOM,
    WAR_WALL_PIECE_T_RIGHT,
    WAR_WALL_PIECE_CROSS,
    WAR_WALL_PIECE_TOP_LEFT,
    WAR_WALL_PIECE_HORIZONTAL,
    WAR_WALL_PIECE_T_TOP,
    WAR_WALL_PIECE_TOP_RIGHT,
} WarWallPieceType;

typedef enum _WarRuinPieceType
{
    WAR_RUIN_PIECE_NONE,
    WAR_RUIN_PIECE_TOP_LEFT,
    WAR_RUIN_PIECE_TOP,
    WAR_RUIN_PIECE_TOP_RIGHT,
    WAR_RUIN_PIECE_LEFT,
    WAR_RUIN_PIECE_CENTER,
    WAR_RUIN_PIECE_RIGHT,
    WAR_RUIN_PIECE_BOTTOM_LEFT,
    WAR_RUIN_PIECE_BOTTOM,
    WAR_RUIN_PIECE_BOTTOM_RIGHT,
    WAR_RUIN_PIECE_TOP_LEFT_INSIDE,
    WAR_RUIN_PIECE_TOP_RIGHT_INSIDE,
    WAR_RUIN_PIECE_BOTTOM_LEFT_INSIDE,
    WAR_RUIN_PIECE_BOTTOM_RIGHT_INSIDE,
    WAR_RUIN_PIECE_DIAG_1,
    WAR_RUIN_PIECE_DIAG_2,
} WarRuinPieceType;

typedef enum _WarTreeTileType
{
    WAR_TREE_NONE,
    WAR_TREE_TOP_LEFT,
    WAR_TREE_TOP,
    WAR_TREE_TOP_RIGHT,
    WAR_TREE_LEFT,
    WAR_TREE_CENTER,
    WAR_TREE_RIGHT,
    WAR_TREE_BOTTOM_LEFT,
    WAR_TREE_BOTTOM,
    WAR_TREE_BOTTOM_RIGHT,
    WAR_TREE_TOP_LEFT_INSIDE,
    WAR_TREE_TOP_RIGHT_INSIDE,
    WAR_TREE_BOTTOM_LEFT_INSIDE,
    WAR_TREE_BOTTOM_RIGHT_INSIDE,
    WAR_TREE_TOP_END,
    WAR_TREE_BOTTOM_END,
    WAR_TREE_VERTICAL,
    WAR_TREE_DIAG_1,
    WAR_TREE_DIAG_2,
    WAR_TREE_CHOPPED,
} WarTreeTileType;

typedef enum _WarUnitActionStepType
{
    WAR_ACTION_STEP_NONE,
    WAR_ACTION_STEP_FRAME,
    WAR_ACTION_STEP_WAIT,
    WAR_ACTION_STEP_ATTACK,
    WAR_ACTION_STEP_SOUND_SWORD,
    WAR_ACTION_STEP_SOUND_FIST,
    WAR_ACTION_STEP_SOUND_FIREBALL,
    WAR_ACTION_STEP_SOUND_CHOPPING,
    WAR_ACTION_STEP_SOUND_CATAPULT,
    WAR_ACTION_STEP_SOUND_ARROW,
    WAR_ACTION_STEP_SOUND_LIGHTNING,
} WarUnitActionStepType;

typedef enum _WarUnitActionType
{
    WAR_ACTION_TYPE_NONE = -1,

    WAR_ACTION_TYPE_IDLE,
    WAR_ACTION_TYPE_WALK,
    WAR_ACTION_TYPE_ATTACK,
    WAR_ACTION_TYPE_DEATH,
    WAR_ACTION_TYPE_HARVEST,
    WAR_ACTION_TYPE_REPAIR,
    WAR_ACTION_TYPE_BUILD,

    WAR_ACTION_TYPE_COUNT
} WarUnitActionType;

typedef enum _WarUnitActionStatus
{
    WAR_ACTION_NOT_STARTED,
    WAR_ACTION_RUNNING,
    WAR_ACTION_FINISHED,
} WarUnitActionStatus;

typedef enum _PathFindingType
{
    PATH_FINDING_BFS,
    PATH_FINDING_ASTAR
} PathFindingType;

typedef enum _WarPathFinderDataType
{
    PATH_FINDER_DATA_EMPTY = 0,
    PATH_FINDER_DATA_STATIC = 1,
    PATH_FINDER_DATA_DYNAMIC = 2,
} WarPathFinderDataType;

typedef enum _WarStateType
{
    WAR_STATE_IDLE,
    WAR_STATE_MOVE,
    WAR_STATE_PATROL,
    WAR_STATE_FOLLOW,
    WAR_STATE_ATTACK,
    WAR_STATE_GOLD,
    WAR_STATE_MINING,
    WAR_STATE_WOOD,
    WAR_STATE_CHOPPING,
    WAR_STATE_DELIVER,
    WAR_STATE_DEATH,
    WAR_STATE_COLLAPSE,
    WAR_STATE_TRAIN,
    WAR_STATE_UPGRADE,
    WAR_STATE_BUILD,
    WAR_STATE_REPAIR,
    WAR_STATE_REPAIRING,
    WAR_STATE_CAST,
    WAR_STATE_WAIT,

    WAR_STATE_COUNT
} WarStateType;

typedef enum _WarTextAlignment
{
    WAR_TEXT_ALIGN_LEFT,
    WAR_TEXT_ALIGN_CENTER,
    WAR_TEXT_ALIGN_RIGHT,
    WAR_TEXT_ALIGN_TOP,
    WAR_TEXT_ALIGN_MIDDLE,
    WAR_TEXT_ALIGN_BOTTOM,

    WAR_TEXT_ALIGN_COUNT
} WarTextAlignment;

typedef enum _WarTextWrapping
{
    WAR_TEXT_WRAP_NONE,
    WAR_TEXT_WRAP_CHAR
} WarTextWrapping;

typedef enum _WarTextTrimming
{
    WAR_TEXT_TRIM_NONE,
    WAR_TEXT_TRIM_SPACES,
    WAR_TEXT_TRIM_ALL
} WarTextTrimming;

typedef enum _WarAudioId
{
    WAR_MUSIC_00 = 0,
    WAR_MUSIC_01 = 1,
    WAR_MUSIC_02 = 2,
    WAR_MUSIC_03 = 3,
    WAR_MUSIC_04 = 4,
    WAR_MUSIC_05 = 5,
    WAR_MUSIC_06 = 6,
    WAR_MUSIC_07 = 7,
    WAR_MUSIC_08 = 8,
    WAR_MUSIC_09 = 9,
    WAR_MUSIC_10 = 10,
    WAR_MUSIC_11 = 11,
    WAR_MUSIC_12 = 12,
    WAR_MUSIC_13 = 13,
    WAR_MUSIC_14 = 14,
    WAR_MUSIC_15 = 15,
    WAR_MUSIC_16 = 16,
    WAR_MUSIC_17 = 17,
    WAR_MUSIC_18 = 18,
    WAR_MUSIC_19 = 19,
    WAR_MUSIC_20 = 20,
    WAR_MUSIC_21 = 21,
    WAR_MUSIC_22 = 22,
    WAR_MUSIC_23 = 23,
    WAR_MUSIC_24 = 24,
    WAR_MUSIC_25 = 25,
    WAR_MUSIC_26 = 26,
    WAR_MUSIC_27 = 27,
    WAR_MUSIC_28 = 28,
    WAR_MUSIC_29 = 29,
    WAR_MUSIC_30 = 30,
    WAR_MUSIC_31 = 31,
    WAR_MUSIC_32 = 32,
    WAR_MUSIC_33 = 33,
    WAR_MUSIC_34 = 34,
    WAR_MUSIC_35 = 35,
    WAR_MUSIC_36 = 36,
    WAR_MUSIC_37 = 37,
    WAR_MUSIC_38 = 38,
    WAR_MUSIC_39 = 39,
    WAR_MUSIC_40 = 40,
    WAR_MUSIC_41 = 41,
    WAR_MUSIC_42 = 42,
    WAR_MUSIC_43 = 43,
    WAR_MUSIC_44 = 44,
    WAR_LOGO = 472,
    WAR_INTRO_DOOR = 473,
    WAR_BUILDING = 474,
    WAR_EXPLOSION = 475,
    WAR_CATAPULT_ROCK_FIRED = 476,
    WAR_TREE_CHOPPING_1 = 477,
    WAR_TREE_CHOPPING_2 = 478,
    WAR_TREE_CHOPPING_3 = 479,
    WAR_TREE_CHOPPING_4 = 480,
    WAR_BUILDING_COLLAPSE_1 = 481,
    WAR_BUILDING_COLLAPSE_2 = 482,
    WAR_BUILDING_COLLAPSE_3 = 483,
    WAR_UI_CHIME = 484,
    WAR_UI_CLICK = 485,
    WAR_UI_CANCEL = 486,
    WAR_SWORD_ATTACK_1 = 487,
    WAR_SWORD_ATTACK_2 = 488,
    WAR_SWORD_ATTACK_3 = 489,
    WAR_FIST_ATTACK = 490,
    WAR_CATAPULT_FIRE_EXPLOSION = 491,
    WAR_FIREBALL = 492,
    WAR_ARROW_SPEAR = 493,
    WAR_ARROW_SPEAR_HIT = 494,
    WAR_ORC_HELP_1 = 495,                           // "The humans draw near"
    WAR_ORC_HELP_2 = 496,                           // "The pale dogs approach"
    WAR_HUMAN_HELP_1 = 497,                         // "The Orcs are approaching"
    WAR_HUMAN_HELP_2 = 498,                         // "There are enemies nearby"
    WAR_ORC_DEAD = 499,
    WAR_HUMAN_DEAD = 500,
    WAR_ORC_WORK_COMPLETE = 501,                    // "Work completed"
    WAR_HUMAN_WORK_COMPLETE = 502,                  // "Work completed"
    WAR_ORC_HELP_3 = 503,                           // "We are being attacked"
    WAR_ORC_HELP_4 = 504,                           // "They're destroying our city"
    WAR_HUMAN_HELP_3 = 505,                         // "We are under attack"
    WAR_HUMAN_HELP_4 = 506,                         // "The town is under attack"
    WAR_ORC_READY = 507,                            // "Your command, master"
    WAR_HUMAN_READY = 508,                          // "Your command"
    WAR_ORC_ACKNOWLEDGEMENT_1 = 509,
    WAR_ORC_ACKNOWLEDGEMENT_2 = 510,
    WAR_ORC_ACKNOWLEDGEMENT_3 = 511,
    WAR_ORC_ACKNOWLEDGEMENT_4 = 512,
    WAR_HUMAN_ACKNOWLEDGEMENT_1 = 513,              // "Yes"
    WAR_HUMAN_ACKNOWLEDGEMENT_2 = 514,              // "Yes, mylord"
    WAR_ORC_SELECTED_1 = 515,
    WAR_ORC_SELECTED_2 = 516,
    WAR_ORC_SELECTED_3 = 517,
    WAR_ORC_SELECTED_4 = 518,
    WAR_ORC_SELECTED_5 = 519,
    WAR_HUMAN_SELECTED_1 = 520,                     // "Yes?"
    WAR_HUMAN_SELECTED_2 = 521,                     // "Your will, sire?"
    WAR_HUMAN_SELECTED_3 = 522,                     // "Mylord?"
    WAR_HUMAN_SELECTED_4 = 523,                     // "My liege?"
    WAR_HUMAN_SELECTED_5 = 524,                     // "Your bidding?"
    WAR_ORC_ANNOYED_1 = 525,
    WAR_ORC_ANNOYED_2 = 526,
    WAR_ORC_ANNOYED_3 = 527,                        // "Stop poking me"
    WAR_HUMAN_ANNOYED_1 = 528,                      // "What?!"
    WAR_HUMAN_ANNOYED_2 = 529,                      // "What do you want?!"
    WAR_HUMAN_ANNOYED_3 = 530,                      // "Why do you keep touching me?!"
    WAR_DEAD_SPIDER_SCORPION = 531,
    WAR_NORMAL_SPELL = 532,
    WAR_BUILD_ROAD = 533,
    WAR_ORC_TEMPLE = 534,
    WAR_HUMAN_CHURCH = 535,
    WAR_ORC_KENNEL = 536,
    WAR_HUMAN_STABLE = 537,
    WAR_BLACKSMITH = 538,
    WAR_FIRE_CRACKLING = 539,
    WAR_CANNON = 540,
    WAR_CANNON2 = 541,
    WAR_CAMPAIGNS_HUMAN_ENDING_1 = 542,
    WAR_CAMPAIGNS_HUMAN_ENDING_2 = 543,
    WAR_CAMPAIGNS_ORC_ENDING_1 = 544,
    WAR_CAMPAIGNS_ORC_ENDING_2 = 545,
    WAR_INTRO_1 = 546,                              // "In the age of chaos..."
    WAR_INTRO_2 = 547,                              // "The kingdom of Azeroth was..."
    WAR_INTRO_3 = 548,                              // "No one knew where these..."
    WAR_INTRO_4 = 549,                              // "With an ingenious..."
    WAR_INTRO_5 = 550,                              // "Welcome to the World of Warcraft"
    WAR_CAMPAIGNS_HUMAN_01_INTRO = 551,
    WAR_CAMPAIGNS_HUMAN_02_INTRO = 552,
    WAR_CAMPAIGNS_HUMAN_03_INTRO = 553,
    WAR_CAMPAIGNS_HUMAN_04_INTRO = 554,
    WAR_CAMPAIGNS_HUMAN_05_INTRO = 555,
    WAR_CAMPAIGNS_HUMAN_06_INTRO = 556,
    WAR_CAMPAIGNS_HUMAN_07_INTRO = 557,
    WAR_CAMPAIGNS_HUMAN_08_INTRO = 558,
    WAR_CAMPAIGNS_HUMAN_09_INTRO = 559,
    WAR_CAMPAIGNS_HUMAN_10_INTRO = 560,
    WAR_CAMPAIGNS_HUMAN_11_INTRO = 561,
    WAR_CAMPAIGNS_HUMAN_12_INTRO = 562,
    WAR_CAMPAIGNS_ORC_01_INTRO = 563,
    WAR_CAMPAIGNS_ORC_02_INTRO = 564,
    WAR_CAMPAIGNS_ORC_03_INTRO = 565,
    WAR_CAMPAIGNS_ORC_04_INTRO = 566,
    WAR_CAMPAIGNS_ORC_05_INTRO = 567,
    WAR_CAMPAIGNS_ORC_06_INTRO = 568,
    WAR_CAMPAIGNS_ORC_07_INTRO = 569,
    WAR_CAMPAIGNS_ORC_08_INTRO = 570,
    WAR_CAMPAIGNS_ORC_09_INTRO = 571,
    WAR_CAMPAIGNS_ORC_10_INTRO = 572,
    WAR_CAMPAIGNS_ORC_11_INTRO = 573,
    WAR_CAMPAIGNS_ORC_12_INTRO = 574,
    WAR_HUMAN_DEFEAT = 575,                         // "Your failure in battle"
    WAR_ORC_DEFEAT = 576,                           // "You pitiful"
    WAR_ORC_VICTORY_1 = 577,                        // "The feel of bones"
    WAR_ORC_VICTORY_2 = 578,                        // "If only the worthless"
    WAR_ORC_VICTORY_3 = 579,                        // "Gaze upon the destruction"
    WAR_HUMAN_VICTORY_1 = 580,                      // "The forces of darkness"
    WAR_HUMAN_VICTORY_2 = 581,                      // "Even these children"
    WAR_HUMAN_VICTORY_3 = 582,                      // "Cheers of victory"
} WarAudioId;

typedef enum _WarAudioType
{
    WAR_AUDIO_MIDI,
    WAR_AUDIO_WAVE
} WarAudioType;

typedef enum _WarCursorType
{
    WAR_CURSOR_ARROW = 263,
    WAR_CURSOR_INVALID = 264,
    WAR_CURSOR_YELLOW_CROSSHAIR = 265,
    WAR_CURSOR_RED_CROSSHAIR = 266,
    WAR_CURSOR_YELLOW_CROSSHAIR_2 = 267,
    WAR_CURSOR_MAGNIFYING_GLASS = 268,
    WAR_CURSOR_GREEN_CROSSHAIR = 269,
    WAR_CURSOR_WATCH = 270,
    WAR_CURSOR_ARROW_UP = 271,
    WAR_CURSOR_ARROW_UP_RIGHT = 272,
    WAR_CURSOR_ARROW_RIGHT = 273,
    WAR_CURSOR_ARROW_BOTTOM_RIGHT = 274,
    WAR_CURSOR_ARROW_BOTTOM = 275,
    WAR_CURSOR_ARROW_BOTTOM_LEFT = 276,
    WAR_CURSOR_ARROW_LEFT = 277,
    WAR_CURSOR_ARROW_UP_LEFT = 278
} WarCursorType;

typedef enum _WarProjectileType
{
    WAR_PROJECTILE_ARROW,
    WAR_PROJECTILE_CATAPULT,
    WAR_PROJECTILE_FIREBALL,
    WAR_PROJECTILE_FIREBALL_2,
    WAR_PROJECTILE_WATER_ELEMENTAL,
    WAR_PROJECTILE_RAIN_OF_FIRE
} WarProjectileType;

typedef enum _WarMapTilesetType
{
    MAP_TILESET_FOREST,
    MAP_TILESET_SWAMP,
    MAP_TILESET_DUNGEON
} WarMapTilesetType;

typedef enum _WarFogPieceType
{
    WAR_FOG_PIECE_NONE,
    WAR_FOG_PIECE_TOP_LEFT,
    WAR_FOG_PIECE_TOP,
    WAR_FOG_PIECE_TOP_RIGHT,
    WAR_FOG_PIECE_LEFT,
    WAR_FOG_PIECE_CENTER,
    WAR_FOG_PIECE_RIGHT,
    WAR_FOG_PIECE_BOTTOM_LEFT,
    WAR_FOG_PIECE_BOTTOM,
    WAR_FOG_PIECE_BOTTOM_RIGHT
} WarFogPieceType;

typedef enum _WarFogBoundaryType
{
    WAR_FOG_BOUNDARY_NONE,
    WAR_FOG_BOUNDARY_UNKOWN,
    WAR_FOG_BOUNDARY_FOG,
} WarFogBoundaryType;

typedef enum _WarUnitPortraits
{
    WAR_PORTRAIT_FOOTMAN,
    WAR_PORTRAIT_GRUNT,
    WAR_PORTRAIT_CONJURER,
    WAR_PORTRAIT_WARLOCK,
    WAR_PORTRAIT_PEASANT,
    WAR_PORTRAIT_PEON,
    WAR_PORTRAIT_CATAPULT_HUMANS,
    WAR_PORTRAIT_CATAPULT_ORCS,
    WAR_PORTRAIT_KNIGHT,
    WAR_PORTRAIT_RAIDER,
    WAR_PORTRAIT_ARCHER,
    WAR_PORTRAIT_SPEARMAN,
    WAR_PORTRAIT_CLERIC,
    WAR_PORTRAIT_NECROLYTE,
    WAR_PORTRAIT_FARM_HUMANS,
    WAR_PORTRAIT_FARM_ORCS,
    WAR_PORTRAIT_BARRACKS_HUMANS,
    WAR_PORTRAIT_BARRACKS_ORCS,
    WAR_PORTRAIT_TOWER_HUMANS,
    WAR_PORTRAIT_TOWER_ORCS,
    WAR_PORTRAIT_TOWNHALL_HUMANS,
    WAR_PORTRAIT_TOWNHALL_ORCS,
    WAR_PORTRAIT_LUMBERMILL_HUMANS,
    WAR_PORTRAIT_LUMBERMILL_ORCS,
    WAR_PORTRAIT_STABLE,
    WAR_PORTRAIT_KENNEL,
    WAR_PORTRAIT_BLACKSMITH_HUMANS,
    WAR_PORTRAIT_BLACKSMITH_ORCS,
    WAR_PORTRAIT_CHURCH,
    WAR_PORTRAIT_TEMPLE,
    WAR_PORTRAIT_GOLDMINE,
    WAR_PORTRAIT_STORMWIND,
    WAR_PORTRAIT_BLACKROCK,
    WAR_PORTRAIT_MOVE_HUMANS,
    WAR_PORTRAIT_MOVE_ORCS,
    WAR_PORTRAIT_REPAIR,
    WAR_PORTRAIT_HARVEST,
    WAR_PORTRAIT_BUILD_BASIC,
    WAR_PORTRAIT_BUILD_ADVANCED,
    WAR_PORTRAIT_DELIVER,
    WAR_PORTRAIT_CANCEL,
    WAR_PORTRAIT_WALL,
    WAR_PORTRAIT_ROAD,
    WAR_PORTRAIT_UNKOWN,
    WAR_PORTRAIT_OGRE,
    WAR_PORTRAIT_SPIDER,
    WAR_PORTRAIT_SLIME,
    WAR_PORTRAIT_FIRE_ELEMENTAL,
    WAR_PORTRAIT_SCORPION,
    WAR_PORTRAIT_SKELETON,
    WAR_PORTRAIT_DEAD,
    WAR_PORTRAIT_DAEMON,
    WAR_PORTRAIT_WATER_ELEMENTAL,
    WAR_PORTRAIT_LOTHAR,
    WAR_PORTRAIT_MEDIVH,
    WAR_PORTRAIT_GRIZELDA,
    WAR_PORTRAIT_GARONA,
    WAR_PORTRAIT_WOUNDED,
    WAR_PORTRAIT_BRIGAND,
    WAR_PORTRAIT_HOLY_LANCE,
    WAR_PORTRAIT_ELEMENTAL_BLAST,
    WAR_PORTRAIT_SHADOW_SPEAR,
    WAR_PORTRAIT_FIREBALL,
    WAR_PORTRAIT_SWORD_1,
    WAR_PORTRAIT_SWORD_2,
    WAR_PORTRAIT_SWORD_3,
    WAR_PORTRAIT_AXE_1,
    WAR_PORTRAIT_AXE_2,
    WAR_PORTRAIT_AXE_3,
    WAR_PORTRAIT_WOLVES_1,
    WAR_PORTRAIT_WOLVES_2,
    WAR_PORTRAIT_ARROW_1,
    WAR_PORTRAIT_ARROW_2,
    WAR_PORTRAIT_ARROW_3,
    WAR_PORTRAIT_SPEAR_1,
    WAR_PORTRAIT_SPEAR_2,
    WAR_PORTRAIT_SPEAR_3,
    WAR_PORTRAIT_HORSE_1,
    WAR_PORTRAIT_HORSE_2,
    WAR_PORTRAIT_SHIELD_1_HUMANS,
    WAR_PORTRAIT_SHIELD_2_HUMANS,
    WAR_PORTRAIT_SHIELD_3_HUMANS,
    WAR_PORTRAIT_SHIELD_1_ORCS,
    WAR_PORTRAIT_SHIELD_2_ORCS,
    WAR_PORTRAIT_SHIELD_3_ORCS,
    WAR_PORTRAIT_HEALING,
    WAR_PORTRAIT_FAR_SIGHT,
    WAR_PORTRAIT_INVISIBILITY,
    WAR_PORTRAIT_RAIN_OF_FIRE,
    WAR_PORTRAIT_RAISE_DEAD,
    WAR_PORTRAIT_DARK_VISION,
    WAR_PORTRAIT_UNHOLY_ARMOR,
    WAR_PORTRAIT_POISON_CLOUD
} WarUnitPortraits;

typedef enum _WarMapTileState
{
    MAP_TILE_STATE_UNKOWN = 1,
    MAP_TILE_STATE_FOG = 2,
    MAP_TILE_STATE_VISIBLE = 4
} WarMapTileState;

typedef enum _WarAICommandStatus
{
    WAR_AI_COMMAND_STATUS_CREATED,
    WAR_AI_COMMAND_STATUS_STARTED,
    WAR_AI_COMMAND_STATUS_COMPLETED,
} WarAICommandStatus;

typedef enum _WarAICommandType
{
    WAR_AI_COMMAND_REQUEST,
    WAR_AI_COMMAND_WAIT,
    WAR_AI_COMMAND_ATTACK,
    WAR_AI_COMMAND_DEFEND,
    WAR_AI_COMMAND_SLEEP,

    WAR_AI_COMMAND_COUNT
} WarAICommandType;

typedef enum _WarCheat
{
    WAR_CHEAT_NONE,

    // original cheats
    WAR_CHEAT_GOLD,
    WAR_CHEAT_SPELLS,
    WAR_CHEAT_UPGRADES,
    WAR_CHEAT_END,
    WAR_CHEAT_ENABLE,
    WAR_CHEAT_GOD_MODE,
    WAR_CHEAT_WIN,
    WAR_CHEAT_LOSS,
    WAR_CHEAT_FOG,
    WAR_CHEAT_SKIP_HUMAN,
    WAR_CHEAT_SKIP_ORC,
    WAR_CHEAT_SPEED,

    // custom cheats
    WAR_CHEAT_MUSIC,
    WAR_CHEAT_SOUND,
    WAR_CHEAT_MUSIC_VOL,
    WAR_CHEAT_SOUND_VOL,
    WAR_CHEAT_GLOBAL_SCALE,
    WAR_CHEAT_GLOBAL_SPEED,
    WAR_CHEAT_EDIT,
    WAR_CHEAT_ADD_UNIT,
    WAR_CHEAT_RAIN_OF_FIRE,

    WAR_CHEAT_COUNT
} WarCheat;

typedef enum _WarMapSpeed
{
    WAR_SPEED_SLOWEST,
    WAR_SPEED_SLOW,
    WAR_SPEED_NORMAL,
    WAR_SPEED_FASTER,
    WAR_SPEED_FASTEST
} WarMapSpeed;

typedef enum _WarSceneType
{
    WAR_SCENE_DOWNLOAD,
    WAR_SCENE_BLIZZARD,
    WAR_SCENE_MAIN_MENU,
    WAR_SCENE_BRIEFING,

    WAR_SCENE_COUNT
} WarSceneType;

typedef enum _WarSceneDownloadState
{
    WAR_SCENE_DOWNLOAD_DOWNLOAD,
    WAR_SCENE_DOWNLOAD_CONFIRM,
    WAR_SCENE_DOWNLOAD_DOWNLOADING,
    WAR_SCENE_DOWNLOAD_DOWNLOADED,
    WAR_SCENE_DOWNLOAD_FILE_LOADED,
    WAR_SCENE_DOWNLOAD_FAILED,
} WarSceneDownloadState;
